In [1]:
# Run Chameleon Algorithm 

In [2]:
import numpy as np
import pandas as pd
from os import path
import sys
sys.path.append('./')
from create_metrics import read_data,knn_metric,similarity_metric


In [3]:
# Read Twitter Dataset
DE = read_data.ReadData(path='/Users/vankhaido/HUST/GR2/TwitterDataset/DE/DE_')
nparray_data =  DE.get_df_general()
similarity_result = similarity_metric.Jaccard_similarity_metric(nparray_data)


SIZE:  9497


In [ ]:
print(nparray_data)
print(similarity_result)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1.         0.05263158 0.04       ... 0.         0.         0.        ]
 [0.05263158 1.         0.01960784 ... 0.         0.         0.        ]
 [0.04       0.01960784 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 1.         1.         1.        ]]


In [ ]:
knn_result = knn_metric.Knn_metric(similarity_result,k=20)
knn_result

array([[  33, 1124, 4770, ..., 4631, 1757, 2432],
       [3776, 7482, 1318, ..., 1578,  356, 3743],
       [ 206, 1647, 7347, ..., 2045, 2171, 2279],
       ...,
       [7748, 1430, 7872, ..., 7856, 7858, 9497],
       [7748, 1430, 7872, ..., 7856, 7858, 9497],
       [ 463, 8084, 2631, ..., 5855, 8817, 4407]])

In [ ]:
from graph_partitioning import create_Graphnetworkx
import networkx as nx
# import graph_partitioning.create_subgraph
# from graph_partitioning import create_subgraph
graph = create_Graphnetworkx.Graph(knn_result)
G = graph.createGraphFromAjacentList()
print(G)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [ ]:
# Partitioning using Metis
from graph_partitioning import metis_algorithm,create_subgraph
n_cuts,membership = metis_algorithm.partitionGraph(G,nparts=6,recursive=True)
print(membership)
print(n_cuts)

[1, 5, 4, 5, 5, 2, 0, 3, 5, 1, 2, 5, 3, 2, 1, 1, 4, 3, 3, 0, 5, 4, 1, 5, 5, 2, 5, 3, 1, 0, 4, 5, 5, 2, 0, 4, 1, 2, 2, 4, 5, 1, 4, 4, 1, 1, 4, 5, 1, 2, 2, 4, 1, 3, 1, 4, 4, 0, 1, 1, 5, 1, 3, 0, 4, 0, 3, 4, 1, 2, 4, 5, 4, 2, 4, 5, 4, 1, 1, 3, 1, 2, 3, 2, 4, 4, 1, 4, 4, 4, 4, 1, 0, 0, 4, 1, 4, 3, 4, 2, 2, 4, 2, 1, 1, 2, 4, 4, 1, 3, 4, 1, 1, 0, 4, 5, 3, 5, 0, 4, 4, 4, 2, 0, 5, 2, 2, 4, 3, 2, 3, 5, 1, 5, 2, 0, 5, 0, 1, 1, 2, 2, 1, 0, 4, 3, 5, 0, 5, 4, 0, 1, 2, 5, 3, 2, 5, 4, 5, 2, 0, 4, 1, 0, 5, 5, 5, 4, 5, 5, 4, 1, 2, 4, 4, 3, 4, 3, 1, 1, 1, 4, 4, 2, 2, 1, 5, 5, 4, 5, 0, 2, 3, 4, 4, 2, 4, 5, 3, 5, 4, 4, 2, 5, 4, 0, 1, 5, 5, 3, 0, 5, 0, 5, 4, 4, 2, 2, 5, 1, 4, 0, 1, 1, 4, 4, 2, 4, 0, 0, 1, 3, 4, 1, 1, 1, 1, 3, 4, 5, 1, 4, 2, 4, 5, 1, 3, 4, 5, 4, 5, 4, 0, 1, 5, 4, 5, 4, 2, 5, 1, 2, 4, 0, 5, 0, 5, 1, 0, 3, 4, 1, 0, 0, 5, 1, 2, 5, 4, 4, 2, 1, 5, 4, 2, 5, 4, 5, 4, 0, 1, 1, 2, 4, 1, 5, 0, 3, 4, 0, 5, 5, 0, 1, 0, 5, 1, 5, 5, 4, 0, 3, 2, 2, 5, 5, 5, 5, 0, 2, 3, 0, 5, 2, 3, 5, 2, 2, 0, 0, 5, 4, 3, 

In [ ]:
# # Make subgraph after partition
# subgraphs = create_subgraph.make_subgraphs(G,membership)
#     # print(subgraphs)
# for i in range(0,len(subgraphs)):
#     print(subgraphs[i])


In [ ]:
# Create a dictionary, key-value = node-label
index = 0
dictionary_label = {}
for node in G.nodes:
    dictionary_label[node] = membership[index]
    index = index + 1
print(dictionary_label)

{0: 1, 1: 5, 2: 4, 3: 5, 4: 5, 5: 2, 6: 0, 7: 3, 8: 5, 9: 1, 10: 2, 11: 5, 12: 3, 13: 2, 14: 1, 15: 1, 16: 4, 17: 3, 18: 3, 19: 0, 20: 5, 21: 4, 22: 1, 23: 5, 24: 5, 25: 2, 26: 5, 27: 3, 28: 1, 29: 0, 30: 4, 31: 5, 32: 5, 33: 2, 34: 0, 35: 4, 36: 1, 37: 2, 38: 2, 39: 4, 40: 5, 41: 1, 42: 4, 43: 4, 44: 1, 45: 1, 46: 4, 47: 5, 48: 1, 49: 2, 50: 2, 51: 4, 52: 1, 53: 3, 54: 1, 55: 4, 56: 4, 57: 0, 58: 1, 59: 1, 60: 5, 61: 1, 62: 3, 63: 0, 64: 4, 65: 0, 66: 3, 67: 4, 68: 1, 69: 2, 70: 4, 71: 5, 72: 4, 73: 2, 74: 4, 75: 5, 76: 4, 77: 1, 78: 1, 79: 3, 80: 1, 81: 2, 82: 3, 83: 2, 84: 4, 85: 4, 86: 1, 87: 4, 88: 4, 89: 4, 90: 4, 91: 1, 92: 0, 93: 0, 94: 4, 95: 1, 96: 4, 97: 3, 98: 4, 99: 2, 100: 2, 101: 4, 102: 2, 103: 1, 104: 1, 105: 2, 106: 4, 107: 4, 108: 1, 109: 3, 110: 4, 111: 1, 112: 1, 113: 0, 114: 4, 115: 5, 116: 3, 117: 5, 118: 0, 119: 4, 120: 4, 121: 4, 122: 2, 123: 0, 124: 5, 125: 2, 126: 2, 127: 4, 128: 3, 129: 2, 130: 3, 131: 5, 132: 1, 133: 5, 134: 2, 135: 0, 136: 5, 137: 0, 138: 

In [ ]:
label_ids = list(set(membership))
label_ids

[0, 1, 2, 3, 4, 5]

In [ ]:
import networkx as nx
def make_sub(G:nx.Graph,id,knn_result,dictionary_label):
    # print(G)
    l = len(knn_result)
    g = nx.Graph()
    for key,value in dictionary_label.items():
        if value == id:
            # print(key)
            g.add_node(key)
    l_nodes = list(g.nodes)
    # print(l_nodes)
    size = len(l_nodes)
    # print(type(l_nodes))
    for i in range (0,size):
        for j in range (i+1,size):
            # print(l_nodes[i],l_nodes[j])
            if G.has_edge(l_nodes[i],l_nodes[j]) == True:
                g.add_edge(l_nodes[i],l_nodes[j])
            else:
                continue
    return g



In [ ]:

subgraphs_list=[None]*len(label_ids)
for item in label_ids:
    subgraphs_list[item] = create_subgraph.make_subgraphs(G,item,knn_result,dictionary_label)
    # print(g)
    
for s in subgraphs_list:
    print(s)

Graph with 1583 nodes and 15748 edges
Graph with 1584 nodes and 21406 edges
Graph with 1583 nodes and 20822 edges
Graph with 1582 nodes and 24510 edges
Graph with 1584 nodes and 18068 edges
Graph with 1582 nodes and 17015 edges


In [ ]:
from merge_partitions.relative_closeness import RC 
from merge_partitions.relative_interconnectivity import RI
from merge_partitions.self_similarity import get_selfsimilarity
# for s in subgraphs_list:
rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[1],sub_g2=subgraphs_list[2],membership=membership)
ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[1],sub_g2=subgraphs_list[2],membership=membership)
ss = get_selfsimilarity(rc,ri,2)
print(ss)

2.0146375262995377


In [ ]:
rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[1],sub_g2=subgraphs_list[3],membership=membership)
ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[1],sub_g2=subgraphs_list[4],membership=membership)
ss = get_selfsimilarity(rc,ri,2)
print(ss)

0.007925201190937821


In [ ]:
for i in range (0,len(subgraphs_list)):
    for j in range(i+1,len(subgraphs_list)):
        rc = 0
        ri = 0
        rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
        ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
        ss = get_selfsimilarity(rc,ri,2)
        print("Similarity between cluster ",i,"- ",j,"is: ",ss)

Similarity between cluster  0 -  1 is:  1.8020640287708802
Similarity between cluster  0 -  2 is:  2.6274337053136705
Similarity between cluster  0 -  3 is:  0.2056883013418294
Similarity between cluster  0 -  4 is:  0.13094871531911934
Similarity between cluster  0 -  5 is:  0.867454129266156
Similarity between cluster  1 -  2 is:  2.0146375262995377
Similarity between cluster  1 -  3 is:  0.017071695364957975
Similarity between cluster  1 -  4 is:  0.40204559782674465
Similarity between cluster  1 -  5 is:  0.44687490420732723
Similarity between cluster  2 -  3 is:  0.01659459834083862
Similarity between cluster  2 -  4 is:  0.13252264348755155
Similarity between cluster  2 -  5 is:  0.24624330077864234
Similarity between cluster  3 -  4 is:  0.15836521455087582
Similarity between cluster  3 -  5 is:  0.08625091946285675
Similarity between cluster  4 -  5 is:  2.438922337267383


# Merge Cluster 0 - 2

In [ ]:
from merge_partitions import merge_graphs
new_gr,subgraphs = merge_graphs.merge(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[0],sub_g2=subgraphs_list[1],membership=membership)
print(new_gr)
for gr in subgraphs:
    print(gr)

Graph with 3167 nodes and 39193 edges
Graph with 3167 nodes and 39193 edges
None
Graph with 1583 nodes and 20822 edges
Graph with 1582 nodes and 24510 edges
Graph with 1584 nodes and 18068 edges
Graph with 1582 nodes and 17015 edges


In [ ]:
for i in range (0,len(subgraphs_list)):
    for j in range(i+1,len(subgraphs_list)):
        rc = 0
        ri = 0
        if(subgraphs_list[i] ==None or subgraphs_list[j]==None):
            ss = 0
        else:
            rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ss = get_selfsimilarity(rc,ri,2)
        print("Similarity between cluster ",i,"- ",j,"is: ",ss)

Similarity between cluster  0 -  1 is:  0
Similarity between cluster  0 -  2 is:  4.05115818807073
Similarity between cluster  0 -  3 is:  0.060690068079271305
Similarity between cluster  0 -  4 is:  0.4666564690576204
Similarity between cluster  0 -  5 is:  1.0990711670320485
Similarity between cluster  1 -  2 is:  0
Similarity between cluster  1 -  3 is:  0
Similarity between cluster  1 -  4 is:  0
Similarity between cluster  1 -  5 is:  0
Similarity between cluster  2 -  3 is:  0.01659459834083862
Similarity between cluster  2 -  4 is:  0.13252264348755155
Similarity between cluster  2 -  5 is:  0.24624330077864234
Similarity between cluster  3 -  4 is:  0.15836521455087582
Similarity between cluster  3 -  5 is:  0.08625091946285675
Similarity between cluster  4 -  5 is:  2.438922337267383


In [ ]:
new_gr,subgraphs = merge_graphs.merge(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[0],sub_g2=subgraphs_list[2],membership=membership)
# print(new_gr)
for gr in subgraphs:
    print(gr)

Graph with 4750 nodes and 65489 edges
None
None
Graph with 1582 nodes and 24510 edges
Graph with 1584 nodes and 18068 edges
Graph with 1582 nodes and 17015 edges


In [ ]:
for i in range (0,len(subgraphs_list)):
    for j in range(i+1,len(subgraphs_list)):
        rc = 0
        ri = 0
        if(subgraphs_list[i] ==None or subgraphs_list[j]==None):
            ss = 0
        else:
            rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ss = get_selfsimilarity(rc,ri,2)
        print("Similarity between cluster ",i,"- ",j,"is: ",ss)

Similarity between cluster  0 -  1 is:  0
Similarity between cluster  0 -  2 is:  0
Similarity between cluster  0 -  3 is:  0.05993568859256836
Similarity between cluster  0 -  4 is:  0.6145815567811621
Similarity between cluster  0 -  5 is:  1.3553138356889873
Similarity between cluster  1 -  2 is:  0
Similarity between cluster  1 -  3 is:  0
Similarity between cluster  1 -  4 is:  0
Similarity between cluster  1 -  5 is:  0
Similarity between cluster  2 -  3 is:  0
Similarity between cluster  2 -  4 is:  0
Similarity between cluster  2 -  5 is:  0
Similarity between cluster  3 -  4 is:  0.15836521455087582
Similarity between cluster  3 -  5 is:  0.08625091946285675
Similarity between cluster  4 -  5 is:  2.438922337267383


In [ ]:
new_gr,subgraphs = merge_graphs.merge(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[4],sub_g2=subgraphs_list[5],membership=membership)
# print(new_gr)
for gr in subgraphs:
    print(gr)

Graph with 4750 nodes and 65489 edges
None
None
Graph with 1582 nodes and 24510 edges
Graph with 3166 nodes and 38467 edges
None


In [ ]:
for i in range (0,len(subgraphs_list)):
    for j in range(i+1,len(subgraphs_list)):
        rc = 0
        ri = 0
        if(subgraphs_list[i] ==None or subgraphs_list[j]==None):
            ss = 0
        else:
            rc = RC(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ri = RI(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[i],sub_g2=subgraphs_list[j],membership=membership)
            ss = get_selfsimilarity(rc,ri,2)
        print("Similarity between cluster ",i,"- ",j,"is: ",ss)

Similarity between cluster  0 -  1 is:  0
Similarity between cluster  0 -  2 is:  0
Similarity between cluster  0 -  3 is:  0.05993568859256836
Similarity between cluster  0 -  4 is:  6.444408745265326
Similarity between cluster  0 -  5 is:  0
Similarity between cluster  1 -  2 is:  0
Similarity between cluster  1 -  3 is:  0
Similarity between cluster  1 -  4 is:  0
Similarity between cluster  1 -  5 is:  0
Similarity between cluster  2 -  3 is:  0
Similarity between cluster  2 -  4 is:  0
Similarity between cluster  2 -  5 is:  0
Similarity between cluster  3 -  4 is:  0.43457886020362657
Similarity between cluster  3 -  5 is:  0
Similarity between cluster  4 -  5 is:  0


In [ ]:
new_gr,subgraphs = merge_graphs.merge(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[0],sub_g2=subgraphs_list[4],membership=membership)
# print(new_gr)
for gr in subgraphs:
    print(gr)

Graph with 7916 nodes and 113030 edges
None
None
Graph with 1582 nodes and 24510 edges
None
None


In [ ]:
new_gr,subgraphs = merge_graphs.merge(G=G,subgraphs=subgraphs_list,sub_g1=subgraphs_list[0],sub_g2=subgraphs_list[3],membership=membership)
# print(new_gr)
for gr in subgraphs:
    print(gr)

Graph with 9498 nodes and 141355 edges
None
None
None
None
None
